package report

import (
	"html/template"
	"io"
)

// WriteHTML renders a self-contained HTML report (no external assets), used
// both for file export and by the web dashboard.
func WriteHTML(w io.Writer, r *Report) error {
	return htmlTemplate.Execute(w, r)
}

var htmlTemplate = template.Must(template.New("report").Parse(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cluster Guardian — {{.ClusterName}}</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; margin: 0; }
  body { font: 15px/1.5 -apple-system, "Segoe UI", Roboto, sans-serif;
         background: #f4f5f7; color: #1d2433; padding: 2rem 1rem; }
  @media (prefers-color-scheme: dark) {
    body { background: #14161c; color: #e6e8ee; }
    .card { background: #1d2028 !important; }
  }
  main { max-width: 880px; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin-bottom: .25rem; }
  .meta { opacity: .65; margin-bottom: 1.5rem; }
  .summary { display: flex; gap: 1rem; flex-wrap: wrap; margin-bottom: 1.5rem; }
  .stat { flex: 1 1 8rem; padding: .75rem 1rem; border-radius: 10px; background: rgba(127,127,127,.12); }
  .stat b { display: block; font-size: 1.4rem; }
  .card { background: #fff; border-radius: 12px; padding: 1rem 1.25rem; margin-bottom: 1rem;
          box-shadow: 0 1px 3px rgba(0,0,0,.08); }
  .card h2 { font-size: 1.05rem; margin-bottom: .5rem; }
  ul { list-style: none; }
  li { padding: .3rem 0; display: flex; gap: .6rem; align-items: baseline; }
  .badge { font-size: .7rem; font-weight: 600; text-transform: uppercase; letter-spacing: .04em;
           padding: .1rem .45rem; border-radius: 99px; white-space: nowrap; }
  .badge.ok       { background: #d9f2e2; color: #1a7f42; }
  .badge.info     { background: #dcebfa; color: #1f5f9e; }
  .badge.warning  { background: #fdeeca; color: #8a6100; }
  .badge.critical { background: #fadada; color: #a12626; }
  .hint { display: block; font-size: .85rem; opacity: .6; margin-left: 0; }
  footer { text-align: center; opacity: .5; font-size: .8rem; margin-top: 2rem; }
</style>
</head>
<body>
<main>
  <h1>🛡️ Cluster: {{.ClusterName}}</h1>
  <p class="meta">Generated {{.GeneratedAt.Format "2006-01-02 15:04 UTC"}}{{with .KubernetesVersion}} · Kubernetes {{.}}{{end}}</p>

  <div class="summary">
    <div class="stat"><b>{{.Summary.Namespaces}}</b>namespaces</div>
    <div class="stat"><b>{{.Summary.Total}}</b>findings</div>
    <div class="stat"><b>{{.Summary.Warnings}}</b>warnings</div>
    <div class="stat"><b>{{.Summary.Critical}}</b>critical</div>
  </div>

  {{range .Namespaces}}{{if .Findings}}
  <section class="card">
    <h2>📦 Namespace: {{.Name}}</h2>
    <ul>
      {{range .Findings}}
      <li><span class="badge {{.Severity}}">{{.Severity}}</span>
        <div>{{.Message}}{{with .Hint}}<span class="hint">{{.}}</span>{{end}}</div></li>
      {{end}}
    </ul>
  </section>
  {{end}}{{end}}

  {{range .Sections}}{{if .Findings}}
  <section class="card">
    <h2>{{.Icon}} {{.Title}}</h2>
    <ul>
      {{range .Findings}}
      <li><span class="badge {{.Severity}}">{{.Severity}}</span>
        <div>{{.Message}}{{with .Hint}}<span class="hint">{{.}}</span>{{end}}</div></li>
      {{end}}
    </ul>
  </section>
  {{end}}{{end}}

  <footer>Generated by Cluster Guardian</footer>
</main>
</body>
</html>
`))
